#!/usr/bin/env bash
# Stop hook — the "feedback" half of plan→work→verify→feedback, wired to THIS
# repo's real verify command. When code changed this session and a verify command
# is configured at .claude/harness-kit.json (generated by harness-kit:introspect),
# it surfaces that command so the work is verified before "done".
#
# Safe by design: it does NOT auto-run the command (no heavy/intrusive execution);
# it reminds. Set "blocking": true in the config to make it enforce instead.
# No-ops silently in any repo without the generated config. Bypass: HARNESS_VERIFY_OFF=1.
set -uo pipefail
[ "${HARNESS_VERIFY_OFF:-0}" = "1" ] && exit 0

# Stand down when we are the reason this turn exists.
#
# Emitting additionalContext (or decision=block) from a Stop hook CONTINUES the turn.
# Claude Code and Codex re-fire this hook when the model next tries to stop, setting
# stop_hook_active=true. The tree is still dirty, so an unguarded hook re-nudges —
# forever. Nudge once per turn, then let the model stop.
#
# Read stdin only when a payload can actually arrive: a bare `cat` blocks forever if
# stdin is a TTY or an inherited pipe nobody closes. No payload → treat as first fire.
hook_input=""
[ -t 0 ] || IFS= read -r -d '' -t 2 hook_input || true
payload_cwd=""
stop_hook_active="false"
if [ -n "$hook_input" ]; then
  IFS=$'\x1f' read -r payload_cwd stop_hook_active < <(printf '%s' "$hook_input" | python3 -c '
import json,sys
try: d=json.load(sys.stdin)
except Exception: d={}
cwd=d.get("cwd", "")
print("\x1f".join([
    cwd if isinstance(cwd, str) else "",
    "true" if d.get("stop_hook_active") is True else "false",
]))
' 2>/dev/null)
fi
[ "$stop_hook_active" = "true" ] && exit 0

runtime="${HARNESS_RUNTIME:-claude}"
proj="${CLAUDE_PROJECT_DIR:-${payload_cwd:-$PWD}}"
cfg="$proj/.claude/harness-kit.json"
[ -f "$cfg" ] || exit 0   # only repos that ran introspect opt in

IFS=$'\x1f' read -r cmd blocking < <(python3 - "$cfg" <<'PY' 2>/dev/null
import json,sys
try: d=json.load(open(sys.argv[1]))
except Exception: d={}
print("\x1f".join([d.get("verify_command","") or "", "true" if d.get("blocking") else "false"]))
PY
)
[ -z "$cmd" ] && exit 0

# Only nudge when something actually changed (cheap; no-op in a clean or non-git repo).
dirty="$(cd "$proj" 2>/dev/null && git status --porcelain 2>/dev/null | head -1)"
[ -z "$dirty" ] && exit 0

msg="harness-kit: changes present — verify before done with: ${cmd}"
if [ "$blocking" = "true" ]; then
  python3 -c 'import json,sys;print(json.dumps({"decision":"block","reason":sys.argv[1]}))' "$msg"
elif [ "$runtime" = "codex" ]; then
  python3 -c 'import json,sys;print(json.dumps({"systemMessage":sys.argv[1]}))' "$msg"
else
  # Non-blocking: surface via the documented Stop channel on STDOUT. A Stop hook's
  # stderr (and plain stdout) on exit 0 is DISCARDED by Claude Code — only
  # hookSpecificOutput.additionalContext continues the turn with the reminder.
  python3 -c 'import json,sys;print(json.dumps({"hookSpecificOutput":{"hookEventName":"Stop","additionalContext":sys.argv[1]}}))' "$msg"
fi
exit 0
