#!/usr/bin/env bash
# Stop hook — the "feedback" half of plan→work→verify→feedback, wired to THIS
# repo's real verify command. When code changed this session and a verify command
# is configured at .claude/harness-kit.json (generated by harness-kit:introspect),
# it surfaces that command so the work is verified before "done".
#
# Safe by design: it does NOT auto-run the command (no heavy/intrusive execution);
# it reminds. Set "blocking": true in the config to make it enforce instead.
# No-ops silently in any repo without the generated config. Bypass: HARNESS_VERIFY_OFF=1.
set -uo pipefail
[ "${HARNESS_VERIFY_OFF:-0}" = "1" ] && exit 0

proj="${CLAUDE_PROJECT_DIR:-$PWD}"
cfg="$proj/.claude/harness-kit.json"
[ -f "$cfg" ] || exit 0   # only repos that ran introspect opt in

IFS=$'\x1f' read -r cmd blocking < <(python3 - "$cfg" <<'PY' 2>/dev/null
import json,sys
try: d=json.load(open(sys.argv[1]))
except Exception: d={}
print("\x1f".join([d.get("verify_command","") or "", "true" if d.get("blocking") else "false"]))
PY
)
[ -z "$cmd" ] && exit 0

# Only nudge when something actually changed (cheap; no-op in a clean or non-git repo).
dirty="$(cd "$proj" 2>/dev/null && git status --porcelain 2>/dev/null | head -1)"
[ -z "$dirty" ] && exit 0

msg="harness-kit: changes present — verify before done with: ${cmd}"
if [ "$blocking" = "true" ]; then
  python3 -c 'import json,sys;print(json.dumps({"decision":"block","reason":sys.argv[1]}))' "$msg"
else
  printf '%s\n' "$msg" >&2
fi
exit 0
