#!/usr/bin/env bash
# Deterministic repo-map generator. Emits a factual navigation map (stack, entry
# points, top-level layout, monorepo members, where tests live) so an agent can
# orient on a whole codebase via progressive disclosure — read the map first, then
# drill into the exact subtree. FACTS ONLY: it never guesses what a module "does"
# (that judgment slot is left for a human/LLM to fill). Re-run to refresh; the map
# is a navigation document, NOT a stored metric.
#
# Usage: repomap.sh <target-dir> [out-file]   (default out: <target>/.claude/repo-map.md)
# Reads configs statically via detect.sh (no eval, no target-code execution).
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
TARGET="${1:?usage: repomap.sh <target-dir> [out-file]}"
OUT="${2:-$TARGET/.claude/repo-map.md}"

command -v python3 >/dev/null 2>&1 || { echo "repomap: python3 not found" >&2; exit 1; }
[ -d "$TARGET" ] || { echo "repomap: target not found: $TARGET" >&2; exit 1; }

json_file="$(mktemp)"
trap 'rm -f "$json_file"' EXIT
bash "$HERE/detect.sh" "$TARGET" 2>/dev/null > "$json_file"
[ -s "$json_file" ] || { echo "repomap: detection failed for $TARGET" >&2; exit 1; }

mkdir -p "$(dirname "$OUT")"

python3 - "$TARGET" "$json_file" "$OUT" <<'PY'
import json, os, sys, glob

target, json_file, out = sys.argv[1], sys.argv[2], sys.argv[3]
d = json.load(open(json_file))

def j(key):
    v = d.get(key)
    return v if v else ""

name = j("project_name") or os.path.basename(os.path.abspath(target)) or "project"
langs = ", ".join(d.get("languages") or [])
fws   = ", ".join(d.get("frameworks") or [])
stores = ", ".join(d.get("data_layer") or [])
members = d.get("members") or []

# Known dir-name → short role label. Heuristic (name-based), flagged as such; an
# unknown dir gets a blank slot for a human to fill, never a fabricated role.
ROLE = {
    "src": "source", "lib": "library source", "app": "application source",
    "apps": "applications (monorepo)", "packages": "packages (monorepo)",
    "pkg": "packages", "cmd": "command entrypoints", "internal": "internal packages",
    "tests": "tests", "test": "tests", "__tests__": "tests", "spec": "tests",
    "docs": "documentation", "doc": "documentation", "examples": "examples",
    "scripts": "scripts", "hooks": "hooks", "skills": "skills", "agents": "agents",
    "templates": "templates", "adapters": "adapters", "config": "configuration",
    "public": "static assets", "assets": "assets", "migrations": "db migrations",
    ".github": "CI / GitHub config", "specs": "specs",
}
VENDOR = {"node_modules", ".git", "dist", "build", ".venv", ".next", "coverage",
          ".turbo", "out", "target", "__pycache__", ".idea", ".vscode", "vendor"}

# Top-level entries (dirs first, files after), excluding vendored/hidden noise.
try:
    entries = sorted(os.listdir(target))
except OSError:
    entries = []
dirs, files = [], []
for e in entries:
    if e in VENDOR:
        continue
    p = os.path.join(target, e)
    if os.path.isdir(p):
        if e.startswith(".") and e not in ROLE:
            continue
        dirs.append(e)
    elif os.path.isfile(p) and not e.startswith("."):
        files.append(e)

# Where tests live — cheap glob of common patterns under the target.
test_hits = []
for pat in ("tests", "test", "**/__tests__"):
    for m in glob.glob(os.path.join(target, pat)):
        if os.path.isdir(m):
            test_hits.append(os.path.relpath(m, target))
for pat in ("**/*_test.*", "**/*.test.*", "**/*.spec.*", "**/*.bats"):
    ms = [m for m in glob.glob(os.path.join(target, pat), recursive=True)
          if not any(v in m.split(os.sep) for v in VENDOR)]
    if ms:
        # summarize the dirs the pattern's matches live in, not every file
        d2 = sorted({os.path.relpath(os.path.dirname(m), target) or "." for m in ms})
        test_hits.append("%s in %s" % (pat, ", ".join(d2[:8]) + ("…" if len(d2) > 8 else "")))
test_hits = sorted(dict.fromkeys(test_hits))

L = []
L.append("# Repo map — %s" % name)
L.append("")
L.append("_Deterministic navigation map generated by `harness-kit:introspect`. "
         "Facts only (stack / entry points / layout / test locations); dir roles "
         "are name-based heuristics — fill responsibilities & invariants by hand. "
         "Re-run introspect to refresh. This is a navigation doc, not a metric._")
L.append("")

L.append("## Stack")
if langs:  L.append("- Languages: %s" % langs)
if fws:    L.append("- Frameworks: %s" % fws)
if stores: L.append("- Data layer: %s" % stores)
if not (langs or fws or stores):
    L.append("- No packaged stack detected (universal spine only).")
L.append("")

ep = []
if j("dev_cmd"):   ep.append("- Dev: `%s`" % j("dev_cmd"))
if j("build_cmd"): ep.append("- Build: `%s`" % j("build_cmd"))
if j("test_cmd"):  ep.append("- Test: `%s`" % j("test_cmd"))
if j("typecheck_cmd"): ep.append("- Typecheck: `%s`" % j("typecheck_cmd"))
if j("lint_cmd"):  ep.append("- Lint: `%s`" % j("lint_cmd"))
if ep:
    L.append("## Entry points")
    L.extend(ep)
    L.append("")

L.append("## Layout (top level)")
for e in dirs:
    role = ROLE.get(e, "")
    L.append("- `%s/`%s" % (e, " — " + role if role else ""))
if files:
    L.append("- Root files: %s" % ", ".join("`%s`" % f for f in files[:20])
             + ("…" if len(files) > 20 else ""))
L.append("")

if d.get("monorepo") and members:
    L.append("## Members (monorepo)")
    L.append("_Each member has its own stack — run `/harness-kit:introspect <member>` "
             "to tailor its architect + critics._")
    for m in members:
        L.append("- `%s`" % m)
    L.append("")

if test_hits:
    L.append("## Where tests live")
    for t in test_hits:
        L.append("- %s" % t)
    L.append("")

open(out, "w").write("\n".join(L).rstrip() + "\n")
print("repomap: wrote %s" % out)
PY
